services:
  ledger_app:
    image: node:latest
    container_name: ledger_app
    working_dir: /usr/src/ledger_app
    env_file:
      - .env
    command: sh -c "npm i -g pnpm && pnpm install && pnpm turbo ${MULT_RUN_ENV}"
    ports:
      - "${LEDGER_APP_PORT}:${LEDGER_APP_PORT}"
      - "3050:3050"

    environment:
      VITE_APP_NETWORK: ${VITE_APP_NETWORK}
      VITE_COLLECTION_ADDRESS: ${VITE_COLLECTION_ADDRESS}
      VITE_SOCIAL_X: ${VITE_SOCIAL_X}
      VITE_SOCIAL_DISCORD: ${VITE_SOCIAL_DISCORD}
      VITE_SOCIAL_TELEGRAM: ${VITE_SOCIAL_TELEGRAM}
      VITE_SOCIAL_HOMEPAGE: ${VITE_SOCIAL_HOMEPAGE}
      VITE_COIN_TYPE: ${VITE_COIN_TYPE}
      VITE_CHAT_PAGE: ${VITE_CHAT_PAGE}
      VITE_PANORA_API_URL: ${VITE_PANORA_API_URL}
      VITE_PANORA_API_KEY: ${VITE_PANORA_API_KEY}
      VITE_BUY_LEDGER: ${VITE_BUY_LEDGER}
      VITE_OPENAI_API_KEY: ${VITE_OPENAI_API_KEY}
      VITE_WAPAL_AGGREGATOR_URL: ${VITE_WAPAL_AGGREGATOR_URL}
      VITE_CREATOR_ADDRESS: ${VITE_CREATOR_ADDRESS}
      VITE_SECONDARY_MARKETPLACE: ${VITE_SECONDARY_MARKETPLACE}
      VITE_AUTO_BACKEND_URL: ${VITE_AUTO_BACKEND_URL}
      VITE_DEV_MODE: ${VITE_DEV_MODE}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ALLOW_ORIGIN: ${ALLOW_ORIGIN}
      AUTO_BACKEND_URL: ${AUTO_BACKEND_URL}
      AUTO_BACKEND_PORT: ${AUTO_BACKEND_PORT}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      STORAGE_CREDENTIALS: ${STORAGE_CREDENTIALS}
      NODE_ENV: ${NODE_ENV}
      PROJECT_ID: ${PROJECT_ID}
      PRIVATE_KEY_SERVER: ${PRIVATE_KEY_SERVER}
    volumes:
      - ./:/usr/src/ledger_app